numpy.ndarray.copy() will create a independent duplication

In [2]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
b = a
c = np.array([1,2,3,4,5,6,7,8,9])
d = c.copy()

a[0] = 100
c[0] = 100

print("\n",a,"\n",b,"\n",c,"\n",d)


 [100   2   3   4   5   6   7   8   9] 
 [100   2   3   4   5   6   7   8   9] 
 [100   2   3   4   5   6   7   8   9] 
 [1 2 3 4 5 6 7 8 9]
