numpy.ndarray.copy() will create a independent duplication

In [2]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
b = a
c = np.array([1,2,3,4,5,6,7,8,9])
d = c.copy()

a[0] = 100
c[0] = 100

print("\n",a,"\n",b,"\n",c,"\n",d)


 [100   2   3   4   5   6   7   8   9] 
 [100   2   3   4   5   6   7   8   9] 
 [100   2   3   4   5   6   7   8   9] 
 [1 2 3 4 5 6 7 8 9]


## indexing

In [3]:
a = np.random.randint(1,100,(3,3))

In [4]:
a

array([[50, 21, 57],
       [94, 77, 92],
       [43, 79, 22]])

In [5]:
print(a[1])

[94 77 92]


In [6]:
print(a[1][1])

77


In [7]:
print(a[1,1])

77


## [start:end:step]

In [9]:
a = np.arange(1,101)

In [11]:
print(a[0:10])

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
print(a[1:20:5])

[ 2  7 12 17]


In [14]:
print(a[::-5])

[100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15
  10   5]


## np.take

In [19]:
a = np.arange(1,26)

In [20]:
a = a.reshape(5,5)

In [21]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
r = [0,2,4]

In [23]:
print(np.take(a,r, axis=0))

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [24]:
print(np.take(a,r, axis=1))

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


## Iterating

## apply_along_axis

In [26]:
a = np.arange(1,82).reshape(9,9)

In [27]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81]])

In [28]:
print(np.apply_along_axis(np.sum,0,a))

[333 342 351 360 369 378 387 396 405]


In [29]:
print(np.apply_along_axis(np.sum,1,a))

[ 45 126 207 288 369 450 531 612 693]


In [30]:
x=np.apply_along_axis(np.sum,1,a)

In [32]:
x_t = x.reshape(1,-1) 

In [33]:
x_t

array([[ 45, 126, 207, 288, 369, 450, 531, 612, 693]])

In [34]:
print(a.reshape(-1,1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]
 [50]
 [51]
 [52]
 [53]
 [54]
 [55]
 [56]
 [57]
 [58]
 [59]
 [60]
 [61]
 [62]
 [63]
 [64]
 [65]
 [66]
 [67]
 [68]
 [69]
 [70]
 [71]
 [72]
 [73]
 [74]
 [75]
 [76]
 [77]
 [78]
 [79]
 [80]
 [81]]


In [35]:
print(a.reshape(1,-1))

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
  73 74 75 76 77 78 79 80 81]]
