In [1]:
import numpy as np

a = np.arange(1,17).reshape(4,4)

In [2]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
b = a.flat

In [6]:
for i in b:
    print("\n",i)


 1

 2

 3

 4

 5

 6

 7

 8

 9

 10

 11

 12

 13

 14

 15

 16


In [13]:
c = a.flatten()

In [14]:
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [15]:
for i in c:
    print("\n",i)


 1

 2

 3

 4

 5

 6

 7

 8

 9

 10

 11

 12

 13

 14

 15

 16


## oder C F A, row, column, default

In [17]:
print(a.flatten(order="C"))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [18]:
print(a.flatten(order="F"))

[ 1  5  9 13  2  6 10 14  3  7 11 15  4  8 12 16]


In [19]:
print(a.flatten(order="A"))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [20]:
print(a.flatten(order="k"))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


## ravel 返回视图,修改视图会影响原始数据

In [22]:
a = np.arange(1,10).reshape(3,3)

In [23]:
b = a.ravel()

In [24]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
b[4]=100

In [27]:
b

array([  1,   2,   3,   4, 100,   6,   7,   8,   9])

In [28]:
a

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

# ravel order F 拷贝

In [29]:
c = a.ravel(order="F")

In [30]:
c

array([  1,   4,   7,   2, 100,   8,   3,   6,   9])

In [31]:
c[0]=99

In [32]:
c

array([ 99,   4,   7,   2, 100,   8,   3,   6,   9])

In [33]:
a

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

# reshape 1-1

In [34]:
print(a.reshape(1,-1)) # reshape to 1 row, and -1 means let numpy determine columns

[[  1   2   3   4 100   6   7   8   9]]


In [35]:
print(a.reshape(-1,1)) # reshape to 1 column, and -1 meanslet numpy determines rows

[[  1]
 [  2]
 [  3]
 [  4]
 [100]
 [  6]
 [  7]
 [  8]
 [  9]]


## transpose ndarray.T , np.transpose(ndarray)

In [36]:
a = np.arange(1,10)

In [37]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a.shape

(9,)

In [39]:
a.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a.T.shape

(9,)

In [42]:
b = np.transpose(a)

In [43]:
b.shape

(9,)

In [44]:
## new_axis adding one dimension

In [47]:
b = a[:, np.newaxis]

In [48]:
c = a[np.newaxis,:]

In [51]:
print(b,"\n","\n",b.shape,"\n","\n",c,"\n","\n",c.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 
 
 (9, 1) 
 
 [[1 2 3 4 5 6 7 8 9]] 
 
 (1, 9)


# np.squeeze() 去掉None维度

In [54]:
d = np.squeeze(c, axis=0)

In [55]:
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
d.shape

(9,)

In [57]:
e = np.squeeze(b,axis=1)

In [58]:
e

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
e.shape

(9,)

## concatenate

In [61]:
x_1 = np.arange(1,9).reshape(2,-1)

In [62]:
x_1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
x_2 = np.arange(9,17).reshape(2,-1)

In [69]:
x_2

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [70]:
np.concatenate([x_1,x_2],axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [71]:
np.concatenate([x_1,x_2],axis=1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

## stack vstack hstack

In [72]:
np.stack([x_1,x_2],axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [73]:
np.stack([x_1,x_2],axis=1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

In [75]:
np.stack((x_1,x_2),axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [76]:
np.stack((x_1,x_2),axis=1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

In [77]:
np.vstack((x_1,x_2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [78]:
np.hstack((x_1,x_2))

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

## split vsplit hsplit

In [79]:
a = np.arange(1,26).reshape(5,5)

In [80]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [81]:
np.split(a,[1,3], axis =0)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])]

In [82]:
np.split(a,[1,3], axis =1)

[array([[ 1],
        [ 6],
        [11],
        [16],
        [21]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23]]),
 array([[ 4,  5],
        [ 9, 10],
        [14, 15],
        [19, 20],
        [24, 25]])]

In [83]:
np.vsplit(a,[2])

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])]

In [84]:
np.hsplit(a,[3])

[array([[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13],
        [16, 17, 18],
        [21, 22, 23]]),
 array([[ 4,  5],
        [ 9, 10],
        [14, 15],
        [19, 20],
        [24, 25]])]

# np.tile 铺开数列

In [85]:
a = np.array([[1,2],
              [3,4]])

In [86]:
a

array([[1, 2],
       [3, 4]])

In [87]:
np.tile(a,(1,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [88]:
np.tile(a,(4,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [89]:
np.tile(a,(3,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

# np.repeat

In [90]:
a = np.arange(1,5).reshape(2,2)

In [91]:
a

array([[1, 2],
       [3, 4]])

In [92]:
np.repeat(a,[2,2],axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [93]:
np.repeat(a,[2,2],axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [94]:
np.repeat(a,3,axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [95]:
np.repeat(a,3,axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])