In [2]:
import numpy as np

## 逻辑判断 np.all np.any

In [3]:
a = np.arange(1,6)

In [4]:
b = a.copy()

In [5]:
a

array([1, 2, 3, 4, 5])

In [6]:
b

array([1, 2, 3, 4, 5])

In [7]:
np.all(a==b)

True

In [8]:
np.any(a==b)

True

In [9]:
b[1] = 693

In [10]:
np.all(a==b)

False

In [11]:
np.any(a==b)

True

# np.isnan

In [12]:
a = [1,2,3, None, 23, 5,4,np.nan, 23,None,2,np.nan]

In [13]:
b = np.array(a)

In [14]:
b

array([1, 2, 3, None, 23, 5, 4, nan, 23, None, 2, nan], dtype=object)

In [16]:
c = np.array([1,2,3,np.nan,4,5,np.nan,6,7])

In [17]:
np.isnan(c)

array([False, False, False,  True, False, False,  True, False, False])

# logical_not logical_and logical_or logical_xor

In [18]:
np.logical_not(1)

False

In [19]:
np.logical_not(0)

True

In [22]:
np.logical_and(1,1)

True

In [27]:
np.logical_and([True,True],[True,False])

array([ True, False])

In [28]:
np.logical_or(True,False)

True

In [30]:
np.logical_or([0,0,1],[1,1,0])

array([ True,  True,  True])

In [31]:
np.logical_xor(1,2)

False

In [32]:
np.logical_xor(1,0)

True

In [34]:
np.logical_xor([True,False,True],[False,False,False])

array([ True, False,  True])

## greater greater_equal equal not_equal less less_equal

In [35]:
np.greater(1,3)

False

In [36]:
np.greater_equal(3,3)

True

In [37]:
np.greater(3,1)

True

In [38]:
np.equal(1,1)

True

In [39]:
np.equal(np.nan, np.nan)

False

In [40]:
np.not_equal(1,2)

True

In [41]:
np.not_equal(np.nan, np.nan)

True

In [42]:
np.less(1,3)

True

In [43]:
np.less_equal(3,3)

True

## isclose allclose

In [44]:
np.isclose(1,1)

True

In [45]:
np.isclose([1,2,3],[1,2,3])

array([ True,  True,  True])

In [46]:
np.allclose([1,2,3],[1,2,3])

True

In [47]:
np.isclose([1,2,3],[1,2,5])

array([ True,  True, False])

In [48]:
np.allclose([1,2,3],[1,2,5])

False