In [2]:
import numpy as np

# broadcasting

In [3]:
a =np.arange(4)

In [4]:
a

array([0, 1, 2, 3])

In [5]:
b = np.ones((3,4))

In [6]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
c = a + b

In [7]:
c

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

# Arithmetic operation

### add

In [3]:
a = np.arange(1,5)

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b = np.ones((3,4))

In [6]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
a+b

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [8]:
np.add(a,b)

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

### subtract

In [9]:
a-b

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [10]:
np.subtract(a,b)

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

### multiply

In [11]:
a * b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [12]:
np.multiply(a,b)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

### divide

In [13]:
a / b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [14]:
np.divide(a,b)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

### floor divide

In [15]:
a//b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [16]:
np.floor_divide(a,b)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

### power

In [7]:
a = np.array([1,2,3,4])
b = np.array([2,4,3,1])

In [8]:
a ** b

array([ 1, 16, 27,  4], dtype=int32)

In [9]:
np.power(a,b)

array([ 1, 16, 27,  4], dtype=int32)

### square sqrt

In [10]:
a = np.array([1,4,9,16,25,36,49,64])

In [11]:
np.sqrt(a)

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [12]:
np.square(a)

array([   1,   16,   81,  256,  625, 1296, 2401, 4096], dtype=int32)

### 三角函数

In [13]:
x = np.linspace(0,2*np.pi,10)

In [14]:
x

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [15]:
np.sin(x)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [16]:
np.cos(x)

array([ 1.        ,  0.76604444,  0.17364818, -0.5       , -0.93969262,
       -0.93969262, -0.5       ,  0.17364818,  0.76604444,  1.        ])

In [17]:
np.tan(x)

array([ 0.00000000e+00,  8.39099631e-01,  5.67128182e+00, -1.73205081e+00,
       -3.63970234e-01,  3.63970234e-01,  1.73205081e+00, -5.67128182e+00,
       -8.39099631e-01, -2.44929360e-16])

In [18]:
np.arcsin(np.sin(x))

array([ 0.00000000e+00,  6.98131701e-01,  1.39626340e+00,  1.04719755e+00,
        3.49065850e-01, -3.49065850e-01, -1.04719755e+00, -1.39626340e+00,
       -6.98131701e-01, -2.44929360e-16])

In [20]:
np.arccos(np.cos(x))

array([0.       , 0.6981317, 1.3962634, 2.0943951, 2.7925268, 2.7925268,
       2.0943951, 1.3962634, 0.6981317, 0.       ])

In [21]:
np.arctan(np.tan(x))

array([ 0.00000000e+00,  6.98131701e-01,  1.39626340e+00, -1.04719755e+00,
       -3.49065850e-01,  3.49065850e-01,  1.04719755e+00, -1.39626340e+00,
       -6.98131701e-01, -2.44929360e-16])

### exponential and logrithm

In [22]:
a = np.arange(1,11)

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.exp2(a)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [27]:
b= np.exp(a)

In [28]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [29]:
c = np.exp2(a)

In [30]:
np.log(b)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
np.log2(c)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## sum cumsum prod cumprod

In [32]:
a = np.arange(1,26).reshape(5,5)

In [33]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
np.sum(a)

325

In [35]:
np.sum(a,axis=0)

array([55, 60, 65, 70, 75])

In [36]:
np.sum(a,axis=1)

array([ 15,  40,  65,  90, 115])

In [37]:
np.cumsum(a)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325],
      dtype=int32)

In [38]:
np.cumsum(a,axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 7,  9, 11, 13, 15],
       [18, 21, 24, 27, 30],
       [34, 38, 42, 46, 50],
       [55, 60, 65, 70, 75]], dtype=int32)

In [39]:
np.cumsum(a,axis=1)

array([[  1,   3,   6,  10,  15],
       [  6,  13,  21,  30,  40],
       [ 11,  23,  36,  50,  65],
       [ 16,  33,  51,  70,  90],
       [ 21,  43,  66,  90, 115]], dtype=int32)

In [40]:
np.prod(a)

2076180480

In [41]:
np.prod(a,axis=0)

array([ 22176,  62832, 129168, 229824, 375000])

In [42]:
np.prod(a,axis=1)

array([    120,   30240,  360360, 1860480, 6375600])

In [43]:
np.cumprod(a)

array([          1,           2,           6,          24,         120,
               720,        5040,       40320,      362880,     3628800,
          39916800,   479001600,  1932053504,  1278945280,  2004310016,
        2004189184,  -288522240,  -898433024,   109641728, -2102132736,
       -1195114496,  -522715136,   862453760,  -775946240,  2076180480],
      dtype=int32)

In [44]:
np.cumprod(a,axis=0)

array([[     1,      2,      3,      4,      5],
       [     6,     14,     24,     36,     50],
       [    66,    168,    312,    504,    750],
       [  1056,   2856,   5616,   9576,  15000],
       [ 22176,  62832, 129168, 229824, 375000]], dtype=int32)

In [45]:
np.cumprod(a,axis=1)

array([[      1,       2,       6,      24,     120],
       [      6,      42,     336,    3024,   30240],
       [     11,     132,    1716,   24024,  360360],
       [     16,     272,    4896,   93024, 1860480],
       [     21,     462,   10626,  255024, 6375600]], dtype=int32)

### np.diff

In [46]:
a = np.arange(1,17).reshape(4,4)

In [48]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
np.diff(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [49]:
np.diff(a,axis=0)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [50]:
np.diff(a,axis=1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### np.round()

In [53]:
a = np.random.rand(3,3) * 10

In [54]:
a

array([[6.18225936, 9.55835404, 3.23867826],
       [8.16746463, 8.34145236, 5.81914739],
       [0.71584634, 0.86572853, 8.4964908 ]])

In [55]:
np.round(a)

array([[ 6., 10.,  3.],
       [ 8.,  8.,  6.],
       [ 1.,  1.,  8.]])

In [56]:
np.round(a, decimals=2)

array([[6.18, 9.56, 3.24],
       [8.17, 8.34, 5.82],
       [0.72, 0.87, 8.5 ]])

### ceil and floor

In [57]:
np.ceil(a)

array([[ 7., 10.,  4.],
       [ 9.,  9.,  6.],
       [ 1.,  1.,  9.]])

In [58]:
np.floor(a)

array([[6., 9., 3.],
       [8., 8., 5.],
       [0., 0., 8.]])

## np.clip

In [63]:
a = np.random.rand(5,5)*10

In [64]:
a = np.round(a)

In [65]:
a

array([[5., 6., 6., 6., 8.],
       [8., 5., 0., 1., 1.],
       [8., 7., 5., 3., 4.],
       [3., 8., 0., 4., 3.],
       [7., 2., 8., 1., 1.]])

In [66]:
np.clip(a, a_min=3,a_max=7)

array([[5., 6., 6., 6., 7.],
       [7., 5., 3., 3., 3.],
       [7., 7., 5., 3., 4.],
       [3., 7., 3., 4., 3.],
       [7., 3., 7., 3., 3.]])

## np.clip  will replace values smaller than min with min, bigger than max with max

## np.absolute np.abs

In [67]:
a = np.array([0,10,-20,-8,7,3,-11,9,-3])

In [68]:
a

array([  0,  10, -20,  -8,   7,   3, -11,   9,  -3])

In [69]:
np.abs(a)

array([ 0, 10, 20,  8,  7,  3, 11,  9,  3])

In [70]:
np.absolute(a)

array([ 0, 10, 20,  8,  7,  3, 11,  9,  3])

## to get sign of values with `np.sign()`

In [72]:
np.sign(a)

array([ 0,  1, -1, -1,  1,  1, -1,  1, -1])