In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,2,3,1,2,3,4,3,2,3,4,3,4,6,8,9,8,67,8,6])

In [3]:
a

array([ 1,  2,  3,  2,  3,  1,  2,  3,  4,  3,  2,  3,  4,  3,  4,  6,  8,
        9,  8, 67,  8,  6])

## np.unique()

In [4]:
np.unique(a)

array([ 1,  2,  3,  4,  6,  8,  9, 67])

In [5]:
u, index = np.unique(a, return_index=True)

In [6]:
print(u,"\n",index)

[ 1  2  3  4  6  8  9 67] 
 [ 0  1  2  8 15 16 17 19]


In [7]:
u , counts = np.unique(a,return_counts=True)

In [8]:
print(u,"\n",counts)

[ 1  2  3  4  6  8  9 67] 
 [2 4 6 3 2 3 1 1]


In [11]:
u,index = np.unique(a, return_inverse=True)

In [12]:
print(u,"\n")
print(index,"\n")
print(u[index],"\n")

[ 1  2  3  4  6  8  9 67] 

[0 1 2 1 2 0 1 2 3 2 1 2 3 2 3 4 5 6 5 7 5 4] 

[ 1  2  3  2  3  1  2  3  4  3  2  3  4  3  4  6  8  9  8 67  8  6] 



## np.in1d()  check if items in set A is also in set B

In [13]:
A = np.array([1,2,3,4,5,6,7,8,9,0,9,8,7,6,5,4,3,2,1])
B = np.array([1,2,3])

In [14]:
np.in1d(A,B)

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True])

## np.union1d()

In [15]:
np.union1d(A,B)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## np.intersect1d

In [16]:
np.intersect1d(A,B)

array([1, 2, 3])

# np.setdiff1d()

In [17]:
np.setdiff1d(A,B)

array([0, 4, 5, 6, 7, 8, 9])

## np.setxor1d() find unique elements in each set

In [18]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])


In [19]:
np.setxor1d(a,b)

array([1, 2, 3, 6, 7, 8])