In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# dot product 点积

In [3]:
np.dot(a,b)

32

# corss product ×积

In [7]:
np.cross(a,b)

array([-3,  6, -3])

In [8]:
A = np.arange(1,5).reshape(2,2)

In [9]:
A

array([[1, 2],
       [3, 4]])

In [11]:
B = np.eye(2)

In [12]:
B

array([[1., 0.],
       [0., 1.]])

In [13]:
np.dot(A,B)

array([[1., 2.],
       [3., 4.]])

In [14]:
np.cross(A,B)

array([-2.,  3.])

# eigenvalue eigenvector

In [16]:
D = np.diag([1,2,3])

In [17]:
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
vals, vecs = np.linalg.eig(D)

In [23]:
for i in vals:
    print(i,"\n")

1.0 

2.0 

3.0 



In [24]:
for j in vecs:
    print(j,"\n")

[1. 0. 0.] 

[0. 1. 0.] 

[0. 0. 1.] 



# SVD 奇异值分解

In [31]:
M = np.round(np.random.rand(12).reshape(4,3)*10)

In [37]:
M

array([[6., 1., 7.],
       [1., 7., 7.],
       [6., 3., 7.],
       [7., 7., 5.]])

In [38]:
u,s,v = np.linalg.svd(M)

In [39]:
u

array([[-0.45382334, -0.57698279, -0.34921399, -0.58239576],
       [-0.46584305,  0.74296383, -0.47212452, -0.08996357],
       [-0.5059957 , -0.313014  , -0.14398875,  0.79073246],
       [-0.56657125,  0.1308352 ,  0.79650189, -0.16572237]])

In [40]:
s

array([18.77838402,  5.90397425,  3.80990572])

In [41]:
v

array([[-0.54268546, -0.48985634, -0.68229997],
       [-0.62350721,  0.77923246, -0.06352581],
       [ 0.56278881,  0.39094442, -0.72830709]])

# QR 分解

In [42]:
q,r = np.linalg.qr(M)

In [43]:
q

array([[-0.54321448,  0.39374623, -0.45901755],
       [-0.09053575, -0.85128376, -0.50894577],
       [-0.54321448,  0.12538288, -0.2528623 ],
       [-0.63375022, -0.32335585,  0.68288927]])

In [44]:
r

array([[-11.04536102,  -7.24285968, -11.407504  ],
       [  0.        ,  -7.45258234,  -3.94186174],
       [  0.        ,   0.        ,  -5.13133302]])

# Chelosky 分解

In [52]:
M = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]])

In [53]:
L = np.linalg.cholesky(M)

In [54]:
L

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

# 范数  Norm 可以理解为向量长度

In [55]:
a = np.array([3,4])

In [56]:
np.linalg.norm(a)

5.0

In [57]:
b = np.array([np.sqrt(2),np.sqrt(2)])

In [58]:
b

array([1.41421356, 1.41421356])

In [59]:
np.linalg.norm(b)

2.0

In [60]:
np.linalg.norm(M)

124.44677577181339

# determinant 行列式 线性变化 面积变换值

In [61]:
det = np.linalg.det(M)

In [62]:
det

36.00000000000003

# Rank of a matrix

In [63]:
M = np.eye(5)

In [64]:
np.linalg.matrix_rank(M)

5

In [65]:
M[0,0]=0

In [66]:
np.linalg.matrix_rank(M)

4

In [67]:
M[4,4]=0

In [68]:
np.linalg.matrix_rank(M)

3

# trace sum over matrix diagnoal

In [69]:
M = np.diag((2,5,3,2,4,1))

In [70]:
M

array([[2, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 1]])

In [71]:
np.trace(M)

17

#  Inverse Matrix, 逆矩阵

## Ax=b 
## x = A<sup>-1</sup> .b

In [75]:
A = np.array([[2,3,5],
              [2,5,8],
              [5,2,2]])

In [76]:
A

array([[2, 3, 5],
       [2, 5, 8],
       [5, 2, 2]])

In [77]:
Ainv = np.linalg.inv(A)

In [78]:
Ainv

array([[ 0.66666667, -0.44444444,  0.11111111],
       [-4.        ,  2.33333333,  0.66666667],
       [ 2.33333333, -1.22222222, -0.44444444]])

In [79]:
b = np.array([7,2,13])

In [80]:
np.linalg.solve(A,b)

array([  5.22222222, -14.66666667,   8.11111111])

In [82]:
np.dot(Ainv,b)

array([  5.22222222, -14.66666667,   8.11111111])